scrape_configs:
  - job_name: "danube-brokers"
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: danube-broker
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - danube-broker1:9040
          - danube-broker2:9040
          - danube-broker3:9040
