apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "etcd.fullname" . } }
  labels:
    app: etcd
spec:
  replicas: { { .Values.etcd.replicaCount } }
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: "{{ .Values.etcd.image.repository }}:{{ .Values.etcd.image.tag }}"
          imagePullPolicy: { { .Values.etcd.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.etcd.service.port } }
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://0.0.0.0:2379"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379"
