apiVersion: v1
kind: Service
metadata:
  name: { { include "etcd.fullname" . } }
  labels:
    app: etcd
spec:
  type: { { .Values.etcd.service.type } }
  ports:
    - port: { { .Values.etcd.service.port } }
      targetPort: 2379
  selector:
    app: etcd
