{{- range $instance := .Values.broker.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "broker.name" $ }}-{{ $instance.name }}
  labels:
    app: {{ include "broker.name" $ }}
    instance: {{ $instance.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "broker.name" $ }}
      instance: {{ $instance.name }}
  template:
    metadata:
      labels:
        app: {{ include "broker.name" $ }}
        instance: {{ $instance.name }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.broker.image.repository }}:{{ $.Values.broker.image.tag }}"
          imagePullPolicy: {{ $.Values.broker.image.pullPolicy }}
          command: ["/usr/local/bin/danube-broker"]
          args: ["--config-file", "/etc/danube_broker.yml", "--advertised-addr", "{{ $instance.host }}"]
          ports:
            - containerPort: {{ $.Values.broker.service.brokerPort }}
              name: broker-port
            - containerPort: {{ $.Values.broker.service.adminPort }}
              name: admin-port
            - containerPort: {{ $.Values.broker.service.promPort }}
              name: prometheus-port
          volumeMounts:
            - name: config-volume
              mountPath: "/etc/danube_broker.yml"
              subPath: "danube_broker.yml"
          env:
            - name: RUST_LOG
              value: {{ $.Values.broker.env.RUST_LOG }}
            - name: BROKER_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: META_STORE_ADDR
              value: {{ include "etcd.addr" $ }}
          resources:
            limits:
              cpu: {{ $.Values.broker.resources.limits.cpu }}
              memory: {{ $.Values.broker.resources.limits.memory }}
            requests:
              cpu: {{ $.Values.broker.resources.requests.cpu }}
              memory: {{ $.Values.broker.resources.requests.memory }}
      volumes:
        - name: config-volume
          configMap:
            name: danube-broker-config
{{- end }}
