apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "broker.name" . }}
  labels:
    app: {{ include "broker.name" . }}
    chart: {{ include "broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.broker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "broker.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "broker.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.broker.image.repository }}:{{ .Values.broker.image.tag }}"
          imagePullPolicy: {{ .Values.broker.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.broker.service.port }}
          env:
            - name: RUST_LOG
              value: {{ .Values.broker.env.RUST_LOG }}
            - name: BROKER_ADDR
              value: {{ .Values.broker.brokerAddr }}
            - name: CLUSTER_NAME
              value: {{ .Values.broker.clusterName }}
            - name: META_STORE_ADDR
              value: {{ include "etcd.addr" . }}
          args:
            - "--broker-addr"
            - "{{ .Values.broker.brokerAddr }}"
            - "--cluster-name"
            - "{{ .Values.broker.clusterName }}"
            - "--meta-store-addr"
            - "{{ include "etcd.addr" . }}"
          resources:
            limits:
              cpu: {{ .Values.broker.resources.limits.cpu }}
              memory: {{ .Values.broker.resources.limits.memory }}
            requests:
              cpu: {{ .Values.broker.resources.requests.cpu }}
              memory: {{ .Values.broker.resources.requests.memory }}
