apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker.name" . }}
  labels:
    app: {{ include "broker.name" . }}
spec:
  type: {{ .Values.broker.service.type }}
  ports:
    - port: {{ .Values.broker.service.port }}
      targetPort: {{ .Values.broker.service.port }}
  selector:
    app: {{ include "broker.name" . }}
