apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker.fullname" . }}-etcd
  labels:
    app: {{ include "broker.name" . }}-etcd
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.etcd.service.type }}
  ports:
    - port: {{ .Values.etcd.service.port }}
      targetPort: {{ .Values.etcd.service.port }}
  selector:
    app: {{ include "broker.name" . }}-etcd
    release: {{ .Release.Name }}
