apiVersion: v1
kind: Service
metadata:
  name:  {{ include "etcd.name" . }}
  labels:
    app:  {{ include "etcd.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.etcd.service.type }}
  ports:
    - port: {{ .Values.etcd.service.port }}
      targetPort: {{ .Values.etcd.service.port }}
  selector:
    app:  {{ include "etcd.name" . }}
    release: {{ .Release.Name }}
