apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.etcd.name }}
  labels:
    app: {{ .Values.etcd.name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.etcd.service.type }}
  ports:
    - port: {{ .Values.etcd.service.port }}
      targetPort: {{ .Values.etcd.service.port }}
  selector:
    app: {{ .Values.etcd.name }}
    release: {{ .Release.Name }}
