apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "broker.name" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"  # Enable gRPC support
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    {{- range $index, $host := .Values.ingress.hosts }}
    - host: {{ $host.host }}  # Host-based routing
  http:
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "broker.serviceName" (printf "%s-%s" (include "broker.name" .) (index .Values.broker.instances $index).name) }}
            port:
              number: {{ .Values.broker.service.brokerPort }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}